### ISSUE TITLE
Schedule Newsletter in CCI (copie carbone invisible)

### ISSUE THREAD

**Issue by JeremyCrealead** [mziech/nextcloud-calendar-news#14]
Hello,
would it be possible for the email address to be registered in CCI instead of A, when sending the newsletters.

thanks in advance.

**Comment by oopen** [comment]
Hi, I fix this privacy problem, in the pull request https://github.com/mziech/nextcloud-calendar-news/pull/15

**Comment by mziech** [comment]
Thank you! I merged your contribution and released version 1.1.6. Sorry for the delay!
