### ISSUE TITLE
interval for sending the newsletter

### ISSUE THREAD

**Issue by aheider** [mziech/nextcloud-calendar-news#2]
Can something be done to also select daily, weekly, monthly, quaterly, 6 months and annual newsletters?
Is this a complicated task?

**Comment by mziech** [comment]
I never finished that implementation because I never needed it for my use-case, but let me see what I can do ...

**Comment by mziech** [comment]
I added a bunch of interval options for yearly, monthly and daily newsletters and also added the option to skip executions, e.g. to have newsletters sent every 2 weeks or every 3 months. Please let me know if you are still missing something.
