### ISSUE TITLE
Mails kommen nicht an

### ISSUE THREAD

**Issue by OliverGraetsch** [mziech/nextcloud-calendar-news#25]
Seit der Aktualisierung auf Version 1.1.10 kommen bei mir keine Mails mehr an (Empfänger: GMX-Postfach, mit GMail ebenfalls getestet).
Weder geplant noch per "Jetzt senden".
Ich habe auf einer gesonderten Nextcloud-Instanz einmal die App installiert. Gleiches Fehlerbild.
Dort habe ich Zugriff aufs Dateisystem und konnte testweise die mit Version 1.1.0 hinzugekommene  Zeile 
`$msg->setTo(["undisclosed-recipients:;"]);  // avoid resend error with majordomo`
aus der NewsletterService.php entfernen.
Ab diesem Zeitpunkt kamen die Mails wieder an.
Leider habe ich keinen Zugriff auf den Mailserver, sodass ich nicht sehen kann, ob die Mail schon beim sendenden Server oder beim emfpangenden Server hängen bleibt.

**Comment by mziech** [comment]
Moin!
Yes, seems like I broke everything while trying to fix something small. I reverted the fix and released version 1.1.11.
Sorry for the inconvenience!
