### ISSUE TITLE
"Error: This app cannot be activated because it makes the server unstable."

### ISSUE THREAD

**Issue by andreasmayerbw** [mziech/nextcloud-calendar-news#28]
Hello,
when I try to activate the app, i get the Error (translated from german to english): "Error: This app cannot be activated because it makes the server unstable."

It is an Nextcloud hosted by https://www.qloc.de/.

Is this a known bug? What can I do to get the app working?

**Comment by joergmschulz** [comment]
This is a known server non-issue https://github.com/nextcloud/server/issues/44685 - you need to adjust your nginx, apache, proxy settings.... I'm in the process of giving up traefik

**Comment by mziech** [comment]
Seems to be answered, thanks!
